import { uid } from "uid";
import { Rule } from "../models/ui.ts";

export const tokiPonaRoot = "Word";

export const tokiPonaRules: Rule[] = [
  {
    name: "Vowel",
    id: uid(),
    terminalOnly: true,
    patterns: [
      { pattern: "a", id: uid(), weight: 1 },
      { pattern: "e", id: uid(), weight: 1 },
      { pattern: "i", id: uid(), weight: 1 },
      { pattern: "o", id: uid(), weight: 1 },
      { pattern: "u", id: uid(), weight: 1 },
    ],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Consonant",
    id: uid(),
    terminalOnly: true,
    patterns: [
      { pattern: "p", id: uid(), weight: 1 },
      { pattern: "t", id: uid(), weight: 1 },
      { pattern: "k", id: uid(), weight: 1 },
      { pattern: "s", id: uid(), weight: 1 },
      { pattern: "m", id: uid(), weight: 1 },
      { pattern: "n", id: uid(), weight: 1 },
      { pattern: "l", id: uid(), weight: 1 },
      { pattern: "w", id: uid(), weight: 1 },
      { pattern: "j", id: uid(), weight: 1 },
    ],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Syllable",
    id: uid(),
    terminalOnly: false,
    patterns: [{ pattern: "Consonant.Vowel.('n')", id: uid(), weight: 1 }],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Word",
    id: uid(),
    terminalOnly: false,
    patterns: [
      { pattern: "(Consonant).Vowel.('n').Syllable{:2}", id: uid(), weight: 1 },
    ],
    rewrites: [
      { match: "'nn'", replace: "'n'", id: uid() },
      { match: "'nm'", replace: "'m'", id: uid() },
    ],
    showRewrites: true,
    exclusions: [
      { match: "'wu'", id: uid() },
      { match: "'wo'", id: uid() },
      { match: "'ji'", id: uid() },
      { match: "'ti'", id: uid() },
    ],
    showExclusions: true,
    collapsed: false,
  },
];
export const tokiPonaWeightedRules: Rule[] = [
  {
    name: "Vowel",
    id: uid(),
    terminalOnly: true,
    patterns: [
      { pattern: "a", id: uid(), weight: 35 },
      { pattern: "e", id: uid(), weight: 25 },
      { pattern: "i", id: uid(), weight: 15 },
      { pattern: "o", id: uid(), weight: 15 },
      { pattern: "u", id: uid(), weight: 10 },
    ],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Consonant",
    id: uid(),
    terminalOnly: true,
    patterns: [
      { pattern: "p", id: uid(), weight: 5 },
      { pattern: "t", id: uid(), weight: 15 },
      { pattern: "k", id: uid(), weight: 15 },
      { pattern: "s", id: uid(), weight: 15 },
      { pattern: "m", id: uid(), weight: 10 },
      { pattern: "n", id: uid(), weight: 10 },
      { pattern: "l", id: uid(), weight: 20 },
      { pattern: "w", id: uid(), weight: 5 },
      { pattern: "j", id: uid(), weight: 5 },
    ],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Coda",
    id: uid(),
    terminalOnly: true,
    patterns: [{ pattern: "n", id: uid(), weight: 1 }],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Rime",
    id: uid(),
    terminalOnly: false,
    patterns: [
      { pattern: "Vowel.Coda", id: uid(), weight: 1 },
      { pattern: "Vowel", id: uid(), weight: 9 },
    ],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },
  {
    name: "Full",
    id: uid(),
    terminalOnly: false,
    patterns: [{ pattern: "Consonant.Rime", id: uid(), weight: 1 }],
    rewrites: [],
    showRewrites: false,
    exclusions: [],
    showExclusions: false,
    collapsed: false,
  },

  {
    name: "Word",
    id: uid(),
    terminalOnly: false,
    patterns: [
      { pattern: "Rime.Full{:2}", id: uid(), weight: 5 },
      { pattern: "Full{1:3}", id: uid(), weight: 95 },
    ],
    rewrites: [
      { match: "'nn'", replace: "'n'", id: uid() },
      { match: "'nm'", replace: "'m'", id: uid() },
    ],
    showRewrites: true,
    exclusions: [
      { match: "'wu'", id: uid() },
      { match: "'wo'", id: uid() },
      { match: "'ji'", id: uid() },
      { match: "'ti'", id: uid() },
    ],
    showExclusions: true,
    collapsed: false,
  },
];

export const tonalRoot = "Syllable";

export const tonalRules: Rule[] = [
  {
    id: uid(),
    name: "Vowel",
    terminalOnly: true,
    showRewrites: false,
    showExclusions: false,
    patterns: [
      { id: uid(), pattern: "a", weight: 2 },
      { id: uid(), pattern: "i", weight: 2 },
      { id: uid(), pattern: "u", weight: 2 },
      { id: uid(), pattern: "e", weight: 1 },
      { id: uid(), pattern: "o", weight: 1 },
      { id: uid(), pattern: "ų", weight: 1 },
      { id: uid(), pattern: "ą", weight: 1 },
    ],
    exclusions: [],
    rewrites: [],
    collapsed: false,
  },
  {
    id: uid(),
    name: "Onset",
    terminalOnly: true,
    showRewrites: false,
    showExclusions: false,
    patterns: [
      { id: uid(), pattern: "t", weight: 3 },
      { id: uid(), pattern: "n", weight: 3 },
      { id: uid(), pattern: "k", weight: 3 },
      { id: uid(), pattern: "l", weight: 3 },
      { id: uid(), pattern: "m", weight: 3 },
      { id: uid(), pattern: "č", weight: 2 },
      { id: uid(), pattern: "s", weight: 2 },
      { id: uid(), pattern: "w", weight: 2 },
      { id: uid(), pattern: "r", weight: 2 },
      { id: uid(), pattern: "d", weight: 2 },
      { id: uid(), pattern: "f", weight: 2 },
      { id: uid(), pattern: "p", weight: 1 },
      { id: uid(), pattern: "b", weight: 1 },
      { id: uid(), pattern: "þ", weight: 1 },
      { id: uid(), pattern: "j", weight: 1 },
      { id: uid(), pattern: "š", weight: 1 },
      { id: uid(), pattern: "c", weight: 1 },
      { id: uid(), pattern: "y", weight: 1 },
      { id: uid(), pattern: "g", weight: 1 },
      { id: uid(), pattern: "z", weight: 1 },
      { id: uid(), pattern: "ð", weight: 1 },
    ],
    exclusions: [],
    rewrites: [],
    collapsed: false,
  },
  {
    id: uid(),
    name: "Medial",
    patterns: [
      { id: uid(), pattern: "u", weight: 1 },
      { id: uid(), pattern: "y", weight: 1 },
    ],
    rewrites: [],
    exclusions: [],
    terminalOnly: true,
    showRewrites: false,
    showExclusions: false,
    collapsed: false,
  },
  {
    id: uid(),
    name: "Coda",
    terminalOnly: true,
    showRewrites: false,
    showExclusions: false,
    patterns: [
      { id: uid(), pattern: "n", weight: 2 },
      { id: uid(), pattern: "ng", weight: 1 },
      { id: uid(), pattern: "m", weight: 1 },
    ],
    exclusions: [],
    rewrites: [],
    collapsed: false,
  },
  {
    id: uid(),
    name: "Tone",
    terminalOnly: true,
    showRewrites: false,
    showExclusions: false,
    patterns: [
      { id: uid(), pattern: "◌̄ ", weight: 1 },
      { id: uid(), pattern: "◌́", weight: 1 },
      { id: uid(), pattern: "◌̀", weight: 1 },
    ],
    exclusions: [],
    rewrites: [],
    collapsed: false,
  },
  {
    id: uid(),
    name: "Syllable",
    terminalOnly: false,
    showRewrites: true,
    showExclusions: true,
    patterns: [
      { id: uid(), pattern: "Onset.(Medial).Vowel.Tone.(Coda)", weight: 1 },
    ],
    exclusions: [
      { id: uid(), match: "'ji'" },
      { id: uid(), match: "'ti'" },
      { id: uid(), match: "'wy'" },
      { id: uid(), match: "'ųu'" },
      { id: uid(), match: "'uų'" },
    ],
    rewrites: [
      { id: uid(), match: "'uu'", replace: "'u'" },
      { id: uid(), match: "'yy'", replace: "'y'" },
      { id: uid(), match: "'yi'", replace: "'i'" },
      { id: uid(), match: "'◌'", replace: "" },
      { id: uid(), match: "'cu'", replace: "'xu'" },
      { id: uid(), match: "['t'/'d'/'c'].'y'", replace: "'chy'" },
      { id: uid(), match: "'yų'", replace: "'ų'" },
    ],
    collapsed: false,
  },
];